queries = `
CREATE TABLE IF NOT EXISTS type_ws (
    id VARCHAR(120) NOT NULL PRIMARY KEY,
    id_ws VARCHAR(120) NOT NULL DEFAULT "NULL",
    kapasitas MEDIUMINT NOT NULL,
    type VARCHAR(120) NOT NULL,
    harga INTEGER NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_ws) REFERENCES workspaces(id) ON DELETE CASCADE ON UPDATE CASCADE
);
`

module.exports = {
    "up": queries,
    "down": ""
}